packages:
  - layers/*
  - projects/*

catalog:
  '@capacitor/android': ^7.4.3
  '@capacitor/assets': ^3.0.5
  '@capacitor/cli': ^7.4.3
  '@capacitor/core': ^7.4.3
  '@capacitor/dialog': ^7.0.2
  '@capacitor/geolocation': ^7.1.5
  '@capacitor/google-maps': ^7.1.1
  '@capacitor/ios': ^7.4.3
  '@capacitor/local-notifications': ^7.0.3
  '@capacitor/preferences': ^7.0.2
  '@capacitor/push-notifications': ^7.0.3
  '@capacitor/splash-screen': ^7.0.3
  '@capacitor/toast': ^7.0.2
  '@nuxt/eslint': 1.9.0
  '@nuxt/fonts': ^0.11.4
  '@nuxt/icon': ^2.0.0
  '@nuxt/kit': ^4.1.2
  '@nuxt/scripts': ^0.11.13
  '@nuxt/test-utils': ^3.19.2
  '@nuxt/ui': 4.0.0-alpha.2
  '@nuxtjs/i18n': 10.1.0
  '@transistorsoft/capacitor-background-fetch': ^7.1.0
  '@transistorsoft/capacitor-background-geolocation': ^7.2.2
  '@trapezedev/project': ^7.1.3
  '@unhead/vue': ^2.0.17
  eslint: ^9.36.0
  eslint-plugin-format: ^1.0.2
  nuxt: ^4.1.2
  tailwindcss: ^4.1.13
  typescript: ^5.9.2
  vite-plugin-eslint2: ^5.0.4
  vue: ^3.5.21
  vue-router: ^4.5.1
  vue-tsc: ^3.0.7

catalogMode: strict

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
