name: 'Build pnpm workspace'
description: 'Runs pnpm install, lints, and builds the project'
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false
    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: |
        COREPACK_EXISTS=$(command -v corepack)
        PNPM_RUNTIME_VERSION="pnpm@$(pnpm --version | cut -d' ' -f3)"
        PACKAGE_JSON_PACKAGE_MANAGER_VERSION=$(cat package.json | grep -o '"packageManager":\s*"[^"]*"' | cut -d'"' -f3)
        PACKAGE_JSON_PNPM_VERSION=$(echo $PACKAGE_JSON_PACKAGE_MANAGER_VERSION | cut -d'+' -f1)

        PNPM_RUNTIME_MATCHES_PACKAGE_JSON=$([[ $PNPM_RUNTIME_VERSION == $PACKAGE_JSON_PNPM_VERSION ]] && echo true || echo false)
        if [ ! -z "$COREPACK_EXISTS" ] || [ $PNPM_RUNTIME_MATCHES_PACKAGE_JSON == "false" ]; then
          npm install -g corepack@latest
        fi
        corepack enable
        pnpm install --frozen-lockfile

    - name: Validate Code Formatting
      shell: bash
      run: pnpm run --parallel lint

    - name: Build Projects
      shell: bash
      run: pnpm run --parallel build

    - name: Test Projects
      shell: bash
      run: pnpm run --parallel test
