name: CI
on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

  workflow_dispatch:
    inputs: {}

  push:
    branches:
      - main


permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: Build
              uses: ./.github/actions/build-pnpm-workspace
              with:
                  upload-build-artifacts: true
                  overwrite-build-artifacts: true
                  build-output-directory: projects/nuxt-v4-mobile-app-with-auth/.output/

    dependabot-check:
        runs-on: ubuntu-latest
        needs: [build]
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v5
              with:
                  sparse-checkout: |
                      ./.github/actions/auto-approve-dependabot
            - name: Check if run is triggered by dependabot
              uses: ./.github/actions/auto-approve-dependabot



