name: CI
on: [pull_request, pull_request_target]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - uses: actions/setup-node@v5
              with:
                  node-version-file: .nvmrc
                  cache: pnpm
            - run: npm install -g corepack@latest && corepack enable && pnpm install --frozen-lockfile
            - uses: ./.github/actions/auto-approve-dependabot