name: CI
on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

  workflow_dispatch:
    inputs: {}

  push:
    branches:
      - main


permissions:
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - uses: actions/setup-node@v5
              with:
                  node-version-file: .nvmrc
                  cache: pnpm
            - run: npm install -g corepack@latest && corepack enable && pnpm install --frozen-lockfile
            - run: pnpm run --parallel lint
            - run: pnpm run --parallel build
    dependabot-check:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: ./.github/actions/auto-approve-dependabot
